issues:
  fix: true

linters:
  enable:
    - typecheck
    - depguard
    - errorlint
    - gocognit
    - gocritic
    - gocyclo
    - gomnd
    - gosec
    - revive
    - stylecheck
    - usestdlibvars
    - gofmt
